/**
 * QRScannerModal — Mobile
 *
 * Uses @capacitor-mlkit/barcode-scanning to open the native Android camera
 * and scan the QR code generated by the Desktop Backup page.
 *
 * On success it parses the JSON payload { v, type, url, key, ts } and
 * calls onPaired({ url, key }) so the parent can save and apply credentials.
 *
 * Falls back to a manual text input if native scanning is unavailable
 * (e.g. running in browser dev mode).
 */

import { useState, useEffect, useRef } from 'react';

const PAYLOAD_TYPE = 'vyaparsetu_pair';
const MAX_AGE_MS = 5 * 60 * 1000; // reject QRs older than 5 minutes

// Returns true if the Capacitor MLKit barcode plugin is available in this runtime
async function isMLKitAvailable() {
  try {
    const mod = await import('@capacitor-mlkit/barcode-scanning');
    // The plugin registers on Capacitor — if Capacitor itself isn't loaded we'll get an error
    return !!(mod && mod.BarcodeScanner);
  } catch (_) {
    return false;
  }
}

async function scanWithMLKit() {
  const { BarcodeScanner, BarcodeFormat } = await import('@capacitor-mlkit/barcode-scanning');

  // Check & request camera permission
  const { camera } = await BarcodeScanner.checkPermissions();
  if (camera !== 'granted') {
    const { camera: granted } = await BarcodeScanner.requestPermissions();
    if (granted !== 'granted') {
      throw new Error('Camera permission was denied. Please allow camera access in Android Settings.');
    }
  }

  const result = await BarcodeScanner.scan({ formats: [BarcodeFormat.QrCode] });

  if (result.barcodes && result.barcodes.length > 0) {
    return result.barcodes[0].rawValue;
  }
  return null;
}

function parsePayload(rawValue) {
  try {
    const data = JSON.parse(rawValue);
    if (data.type !== PAYLOAD_TYPE) {
      throw new Error('This QR code is not from VyapaarSetu Desktop. Please scan the correct QR.');
    }
    if (!data.url || !data.key) {
      throw new Error('QR code is missing credentials. Please regenerate the QR on Desktop.');
    }
    const age = Date.now() - (data.ts || 0);
    if (age > MAX_AGE_MS) {
      throw new Error('This QR code has expired. Please generate a new one on Desktop.');
    }
    return { url: data.url.trim().replace(/\/+$/, ''), key: data.key.trim() };
  } catch (err) {
    if (err.message.includes('QR') || err.message.includes('credential') || err.message.includes('expired')) {
      throw err;
    }
    throw new Error('Could not read QR code. Please ensure you are scanning the VyapaarSetu Desktop QR code.');
  }
}

export default function QRScannerModal({ onPaired, onClose }) {
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [manualMode, setManualMode] = useState(false);
  const [manualJson, setManualJson] = useState('');
  const scanAttemptedRef = useRef(false);

  // Auto-start scan on mount (only once) — falls back to manual mode gracefully
  useEffect(() => {
    if (scanAttemptedRef.current) return;
    scanAttemptedRef.current = true;
    // Check availability before auto-starting so we don't flash an error in browser
    isMLKitAvailable().then((available) => {
      if (available) {
        startScan();
      } else {
        // Running in browser or environment without native plugin — go straight to manual
        setManualMode(true);
      }
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const startScan = async () => {
    setScanning(true);
    setError('');
    try {
      const rawValue = await scanWithMLKit();
      if (!rawValue) {
        // User cancelled — just close silently
        setScanning(false);
        onClose();
        return;
      }
      const creds = parsePayload(rawValue);
      setSuccess(true);
      setScanning(false);
      setTimeout(() => onPaired(creds), 600);
    } catch (err) {
      // Silent close if user pressed Back/cancelled
      if (err?.message?.includes('user cancel') || err?.message?.includes('cancel')) {
        setScanning(false);
        onClose();
        return;
      }
      // Plugin unavailable (browser/Electron) — fall back to manual paste
      const isPluginError = err?.message?.includes('not implemented') ||
                            err?.message?.includes('not available') ||
                            err?.message?.includes('plugin') ||
                            err?.message?.includes('Capacitor');
      if (isPluginError) {
        setManualMode(true);
        setScanning(false);
      } else {
        setError(err.message || 'Scan failed. Please try again or use manual mode.');
        setScanning(false);
      }
    }
  };

  const handleManualSubmit = () => {
    setError('');
    try {
      const creds = parsePayload(manualJson.trim());
      setSuccess(true);
      setTimeout(() => onPaired(creds), 600);
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div
      className="modal-backdrop"
      style={{ zIndex: 9999, alignItems: 'flex-end' }}
      onClick={(e) => { if (e.target === e.currentTarget && !scanning) onClose(); }}
    >
      <div
        className="modal"
        style={{
          width: '100%',
          maxWidth: '100%',
          margin: 0,
          borderRadius: '20px 20px 0 0',
          padding: '28px 20px 36px',
          textAlign: 'center',
          background: 'var(--color-surface)',
          boxShadow: '0 -10px 40px rgba(0,0,0,0.20)',
          animation: 'slideUp 0.28s cubic-bezier(0.34,1.56,0.64,1)',
        }}
      >
        {/* Drag handle */}
        <div style={{ width: 40, height: 4, borderRadius: 2, background: 'var(--color-border)', margin: '0 auto 24px' }} />

        {/* Icon */}
        <div
          style={{
            width: 64,
            height: 64,
            borderRadius: 20,
            background: success
              ? 'linear-gradient(135deg, #10b981, #059669)'
              : 'linear-gradient(135deg, #6366f1 0%, #2563eb 100%)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 16px',
            fontSize: 30,
            transition: 'background 0.3s',
          }}
        >
          {success ? '✅' : scanning ? '📷' : '🔲'}
        </div>

        <h2 style={{ margin: '0 0 8px', fontSize: '1.2rem', fontWeight: 700, color: 'var(--color-text)' }}>
          {success ? 'Paired Successfully!' : scanning ? 'Point at QR Code...' : 'Scan Desktop QR'}
        </h2>
        <p style={{ margin: '0 0 20px', fontSize: '0.875rem', color: 'var(--color-text-muted)', lineHeight: 1.5 }}>
          {success
            ? 'Supabase credentials received. Applying now...'
            : scanning
            ? 'The camera is open. Show the QR code from the Desktop Backup page.'
            : 'Scan the QR code generated from Desktop → Backup → Pair Mobile'}
        </p>

        {error && (
          <div
            style={{
              background: 'var(--color-error-bg)',
              color: 'var(--color-error)',
              borderRadius: 12,
              padding: '12px 16px',
              marginBottom: 20,
              fontSize: '0.875rem',
              textAlign: 'left',
              lineHeight: 1.5,
            }}
          >
            ⚠️ {error}
          </div>
        )}

        {!success && !scanning && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <button
              className="btn btn-primary"
              onClick={startScan}
              style={{ width: '100%', padding: '14px', fontSize: '1rem', borderRadius: 14, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}
            >
              📷 Open Camera &amp; Scan
            </button>
            <button
              className="btn btn-outline"
              onClick={() => setManualMode(v => !v)}
              style={{ width: '100%', padding: '12px', fontSize: '0.9rem', borderRadius: 14 }}
            >
              {manualMode ? 'Hide Manual Entry' : '⌨️ Paste JSON Manually'}
            </button>

            {manualMode && (
              <div style={{ textAlign: 'left', marginTop: 4 }}>
                <label style={{ fontSize: '0.8rem', color: 'var(--color-text-muted)', fontWeight: 600, display: 'block', marginBottom: 6 }}>
                  Paste the JSON copied from Desktop QR modal:
                </label>
                <textarea
                  value={manualJson}
                  onChange={(e) => setManualJson(e.target.value)}
                  rows={4}
                  className="form-input"
                  placeholder='{"v":1,"type":"vyaparsetu_pair","url":"https://...","key":"eyJ..."}'
                  style={{ width: '100%', fontFamily: 'monospace', fontSize: '0.78rem', borderRadius: 10, resize: 'vertical' }}
                />
                <button
                  className="btn btn-primary"
                  onClick={handleManualSubmit}
                  disabled={!manualJson.trim()}
                  style={{ width: '100%', padding: '12px', borderRadius: 12, marginTop: 8 }}
                >
                  Apply Credentials
                </button>
              </div>
            )}

            <button
              className="btn btn-outline"
              onClick={onClose}
              style={{ width: '100%', padding: '12px', borderRadius: 14, color: 'var(--color-text-muted)', borderColor: 'var(--color-border)' }}
            >
              Cancel
            </button>
          </div>
        )}

        {scanning && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
            <div style={{ display: 'flex', gap: 6 }}>
              {[0, 1, 2].map(i => (
                <div
                  key={i}
                  style={{
                    width: 10, height: 10, borderRadius: '50%',
                    background: '#6366f1',
                    animation: `pulse 1.2s ease-in-out ${i * 0.2}s infinite`,
                  }}
                />
              ))}
            </div>
            <p style={{ fontSize: '0.85rem', color: 'var(--color-text-muted)' }}>
              Waiting for camera...
            </p>
            <button
              className="btn btn-outline"
              onClick={() => { setScanning(false); onClose(); }}
              style={{ padding: '10px 28px', borderRadius: 12 }}
            >
              Cancel
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
